---
- name: zapd
  hosts: all
  become: yes
  become_user: root

  vars:
    min_zap: 5000
    max_zap: 10000
  tasks:
    - name: ansible group
      group: 
        name: zapd
        state: present

    - name: ansible user
      user:
        name: zapd
        shell: /usr/sbin/nologin
        groups: zapd
        system: yes
        state: present

    - name: copy zapd.zip
      copy:
        src: ../zapd.zip
        dest: /opt/zapd.zip

    - name: create teh zapd directory
      file:
        path: /opt/zapd
        state: directory
        owner: zapd
        group: zapd
        mode: 0755

    - name: extract zapd.zip with unarchive
      unarchive:
        src: /opt/zapd.zip
        dest: /opt/zapd
        remote_src: yes

    - name: change ownership /opt/zapd
      file:
        dest: /opt/zapd
        owner: zapd
        group: zapd
        recurse: yes

    - name: install python requiremnents
      shell: pip3 install --system -r /opt/zapd/requirements.txt

    - name: set testnet value
      shell: /opt/zapd/set_testnet.py {{ 'true' if TESTNET else 'false' }}

    - name: init wallet address
      shell: /opt/zapd/init_wallet_address.py

    - name: set webhook config
      shell: /opt/zapd/set_webhook_config.py {{ WEBHOOK_URL }} {{ WEBHOOK_KEY }}
      when: KEYS_SUPPLIED

    - name: copy zapd.service
      template:
        src: templates/zapd.service
        dest: /etc/systemd/system/zapd.service

    - name: restart/enable zapd service
      service: name=zapd state=restarted enabled=yes
