---
- name: zapd_cron
  hosts: all 
  become: yes
  become_user: root

  vars:
   min_zap: 2000
   max_zap: 10000

  tasks:
    - name: set cron shell
      cron:
        name: SHELL
        env: yes
        value: /bin/bash

    - name: create the scripts directory
      file:
        path: /root/scripts
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: add cron job to expire transactions
      cron:
        name: expire zapd transactions
        special_time: daily
        job: >
          curl -s -d '{"jsonrpc":"2.0","id":1,"method":"expiretransactions","params":{}}' -H "Content-Type: application/json-rpc" localhost:5000/api

    - name: add cron job to process proposals
      cron:
        name: process zapd proposals
        minute: "*/2"
        job: >
            curl -s -H "Host: {{SERVER_NAME}}" localhost:5000/internal/process_proposals > /dev/null

    - name: add cron job to snapshot dashboard
      cron:
        name: snapshot zapd dashboard
        special_time: hourly
        job: >
          curl -s localhost:5000/dashboard/snapshot > /dev/null
